committt
Ceci-Caccamo/HenryBanks pull request #30
Opened 2020-11-10 23:26 UTC by gabbies86

2020-11-10 23:33 UTC, carlossaballe submitted a review, later dismissed

2020-11-10 23:39 UTC, quasirsg requested changes
Toca  parte de login y register, siendo que hay otro commit de login totalmente distinto y la parte de register ya esta realizada y mergeada. Que se eliminen los cambios a register y login y podra ser mergeado, los demas componentes tocados no afectan a lo ya hecho o son nuevos.

2020-11-11 00:01 UTC, quasirsg approved these changes

2020-11-11 00:02 UTC, CamilolIn approved these changes

2020-11-11 00:02 UTC, merged